### ISSUE TITLE
Game Crash when deleting a Cargo Group with nothing in it

### ISSUE THREAD

**Issue by Mav12222** [pshemk/TF2autosizer#1]
<img width="791" alt="Screenshot 2024-12-07 183838" src="https://github.com/user-attachments/assets/2ce6a2c0-2620-4c34-b803-562482367d5d">

While learning the mod, I created a Cargo group, but did not add anything to it.  I deleted it and the game crashed with the attached error.

**Comment by pshemk** [comment]
Thanks for this report. I replicated and fixed the issue. 
A version with a fix has been published.

**Comment by pshemk** [comment]
Thanks for this report. I replicated and fixed the issue.
A version with a fix has been published.
